export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAILED = "FETCH_CURRENT_USER_FAILED";
export const REGISTER_CURRENT_EMAIL = "REGISTER_CURRENT_EMAIL"
export const REGISTER_CURRENT_PASSWORD = "REGISTER_CURRENT_PASSWORD"
export const REGISTER_CURRENT_USERNAME = "REGISTER_CURRENT_USERNAME"